### ISSUE TITLE
Bugs effecting main

### ISSUE THREAD

**Issue by reganq** [CSC207-2022F-UofT/course-project-uofteams#106]
While setting up main, I've came across a few bugs. Namely, they are: 
- when we click on a post in the postbar, or click filter, the view is only updated when the screen is resized
- The MakePost use case is not adding posts to the respective user that created them
- For the comment, favourite, and delete use cases: we will not be able to put the code to create popups within their views. This is because they are constantly getting reinitialized throughout use. I think the best place for this to be done is the main frame or the post view, as they can both be made to observe the viewmodels

If someone wants to take a look at this, and implement these fixes, that would be wonderful as I am quite tired

**Comment by izumidayo** [comment]
all changes implemented
