### ISSUE TITLE
More Bugs in Main-Frame

### ISSUE THREAD

**Issue by JohannLeidenfrost** [CSC207-2022F-UofT/course-project-uofteams#133]
Filtering posts does not work correctly. When you select a filter by a tag that none of the posts have, the existing list of posts keeps being shown. The issue seems to be that PostListView is not closed so the old view is still visible but also, next to it, we display the defaultDisplay, which says that no posts are available. Need to find a way to replace PostList with defaultDisplay.

**Comment by reganq** [comment]
We had attempted to make it so it would pull all posts, must have gone wrong somewhere there

**Comment by izumidayo** [comment]
Fixed in a different PR/issue/branch
