### ISSUE TITLE
Create a refresh system

### ISSUE THREAD

**Issue by izumidayo** [CSC207-2022F-UofT/course-project-uofteams#82]
**PostListView**================
public void refresh(int deletedPostID)

what it does:
- checks if deletedPostID in this.ids
- IF deletedPostID in this.ids : get index of the deletedPostID in this.id. Using this, remove the title and id of that index from this.titles and this.ids. THEN call displayList(this.titles, this.ids)
- ELSE : do nothing

**ViewPostView**================
public void refresh(int deletedPostID)

what it does:
- check if deletedPostID == this.currentPostID (make sure to catch the exception that is thrown when currentPostID is null)
- IF deletedPostID == this.currentPostID , call displayDefault()
- ELSE : do nothing

Other changes that need to be made to implement the refresh method
- add instance attribute private int currentPostID, which is initially initialized to null
- add getter int getCurrentPostID
- in the method displayPost(), add the following line:
this.currentPostID = outputData.getPostID();
- in the method displayDefault(), add the following line:
this.currentPostID = null;

**Comment by reganq** [comment]
If post is made:
Reset PostListView to default, change ViewPostView to new post
